### PR TITLE
Socket timeout exception

### LINKED ISSUE #52: [BUG] - Socket timeout
### Describe the bug
When running version 0.1.0 and connecting a client successfully a java.net.SocketTimeoutException: Read timed out happens and prints a stacktrace. The application keeps running but no new connections can be made.

### To Reproduce
1. Start the server as a docker container or in IntelliJ.
3. Connect a client and the server will accept the connection.
4. Wait for more than 30 sec.
5. Error message as a stacktrace will be printed in the console:
`java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/java.io.InputStream.read(InputStream.java:220)
	at org.fungover.thunder.PackageReader.isCleanDisconnect(PackageReader.java:65)
	at org.fungover.thunder.ClientHandler.handleConnection(ClientHandler.java:28)
	at org.fungover.thunder.Server.lambda$start$0(Server.java:23)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)`

### Expected behavior
No socket timeout should happen and no stacktrace should be printed to stdout.
Only the first read for a MQTT_CONNECT message need a timeout. After that the timeout should be disabled using socket.setSoTimeout(0); since a connected client might not send anything for a long time.
After a client connects we want a timeout of around 30 seconds when waiting for Connect message and if no such message arrives the client should be disconnected and no stacktrace should be printed but a nicely formatted log message could be used.

### Environment
- OS: docker / linux
- Java Version: 21
- Project Version 0.1.0

### PR DESCRIPTION
**Pull request by Emmelie83**
### Related Issue(s)
Closes #52

### Proposed Changes
 This section is for listing the specific changes you are proposing in this PR. Be clear and concise. For each change, provide a brief description that explains what it does and why it is needed. For beginners, think about what someone would need to know if they have never seen these changes before. Example format:

- **Change 1**: Changing isCleanDisconnect in PackageHandler

### Description
The modifications made to the isCleanDisconnect method ensure that the socket timeout is handled properly. The socket.setSoTimeout(0) in the finally block ensures that the timeout is reset to 0 after attempting to read from the socket, disabling the timeout for subsequent operations.

### Additional Details
- Java Version: [e.g., Java 8, Java 11]
- Project Version: [e.g., 1.0.0]
- Does this change introduce a breaking change? If yes, describe it.

----

| <a href="https://ellipsis.dev" target="_blank">Ellipsis</a> | :rocket: This PR description was created by [Ellipsis](https://www.ellipsis.dev) for commit ab8bd2902a5bdd1c7453b9806072d3045fe30d90.  | 
|--------|--------|

### Summary:
This PR improves socket timeout handling in the `isValidConnection` method of the `PackageReader` class and updates relevant tests.

**Key points**:
- Modified `isValidConnection` method in `PackageReader` class to handle socket timeout.
- Updated `ClientHandlerTest` and `PackageReaderTest` to test new functionality.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by kappsegla** [comment]
Isn't it the method  isValidConnection that has problems with soTimeout? The setting of soTimeout to 30 s should be before the first read attempt on the incomming connection and then after we will set it to 0 to disable the functionality. 
Disconnect messages shouldn't be timed out.

File: src/main/java/org/fungover/thunder/PackageReader.java [hunk 1]
```diff
@@ -62,9 +63,18 @@ public boolean isCleanDisconnect(Socket socket) throws IOException {
...
+        int bytesRead = -1;
+
+        try {
+            socket.setSoTimeout(CONNECTION_TIMEOUT);
+            bytesRead = inputStream.read(buffer);
+        } catch (SocketTimeoutException e) {
+            System.err.println("Socket read timed out.");
+        } finally {
+            socket.setSoTimeout(0);
+        }
```
Comment (Win-ther) [inline src/main/java/org/fungover/thunder/PackageReader.java:75]: You don't need to setSoTimeout(CONNECTION_TIMEOUT) in isCleanDisconnect. It should only timeout if it does not get the CONNECT packet in 30000ms.
Shouldn't putting setSoTimeout(0) after the broker has recieved the CONNECT packet be enough to fix this bug?
image

**Comment by Emmelie83** [comment]
> Isn't it the method isValidConnection that has problems with soTimeout? The setting of soTimeout to 30 s should be before the first read attempt on the incomming connection and then after we will set it to 0 to disable the functionality. Disconnect messages shouldn't be timed out.

Yes, I can see now that you are right. I was looking at the error message saying org.fungover.thunder.PackageReader.isCleanDisconnect(PackageReader.java:65)
I feel that networking is an area where I am really lost. I struggel a lot to understand. That is why I took on this issue, to work with it to get better. Do you have any recommendations for reading or videos on networking? Because we will not have any course on networking, will we?. And it seems important to know.

**Review by Win-ther — APPROVED** [review]
Ser bra ut 🙂

File: src/main/java/org/fungover/thunder/PackageReader.java [hunk 2]
```diff
@@ -18,21 +17,21 @@ public boolean isValidConnection(Socket socket) throws IOException {
         byte[] buffer = new byte[1024];
         InputStream inputStream = socket.getInputStream();
         OutputStream outputStream = socket.getOutputStream();
-        int bytesRead = inputStream.read(buffer);
 
         if (isDoubleConnectMessage(client, buffer)) {
```
Comment (kappsegla) [inline src/main/java/org/fungover/thunder/PackageReader.java:22]: This code might have to be moved since its using buffer for something before we have read anything into the buffer?

**Review by kappsegla — APPROVED** [review]
