### PR TITLE
32 feature handling more than one connection

### LINKED ISSUE #32: [FEATURE] - Handling more than one connection
### Problem Description
At the moment our code in clientHandler.handleConnections() isn't using threads or async I/O and can therefore not handle multiple clients at the same time. Can be seen as some sort of a bug and will have impacts on future developement.

I propose moving the call to serverSocket.accept() into our start method in Server class and then call ClientHandler handleConnection with the retrieved Socket objekt in a new thread.

Since we are using Java21 i propose using virtual threads.
Code suggestions:

```
public void start() {
        try {
            System.out.println("Server started on port 1883");
            while (!serverSocket.isClosed()) {
                Socket connection = null;
                connection = serverSocket.accept();
                Thread.ofVirtual(() -> clientHandler.handleConnection(connection));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

### PR DESCRIPTION
**Pull request by vonfredd**
### Related Issue
Closes #32

### Proposed Changes
 Start a new thread when handling client connections

- **Change 1**: Refactored start method in Server class and create a new thread when connection needs to be handled.
-  **Change 2**: ClientHandler.handleConnection now takes a socket as input parameter. The method is refactored.

### CODE REVIEW

File: src/main/java/org/fungover/thunder/ClientHandler.java [hunk 1]
```diff
@@ -1,33 +1,29 @@
...
-            if (connection != null) {
-                System.out.println("New client: " + connection.getInetAddress().getHostName());
-                clients.add(connection);
+
+    public void handleConnection(Socket clientSocket) {
+        try {
+            while (!clientSocket.isClosed()) {
+                System.out.println("New client: " + clientSocket.getInetAddress().getHostName());
+                clients.add(clientSocket);
+                clientSocket.close();
```
Comment (Win-ther) [inline src/main/java/org/fungover/thunder/ClientHandler.java:19]: The while-loop here does not really do anything since the serverSocket.accept() call was moved to the Server-class. Also the clientSocket.close() call here will make the client disconnect instantly after connecting.

Right now, it will only run once and disconnect the client. If you only remove clientSocket.close(); the while-loop will run forever.

**Review by Win-ther — CHANGES_REQUESTED** [review]
It looks good if you remove the while-loop in clienthandler. It might have conflicts with #24 though?

File: src/main/java/org/fungover/thunder/ClientHandler.java (hunk 1 above)
Comment (vonfredd) [reply src/main/java/org/fungover/thunder/ClientHandler.java:19]: > It looks good if you remove the while-loop in clienthandler. It might have conflicts with #24 though?

Yes, as you say there will probably be alot more method calls between clients.add and socket.close that will handle the outcome of the closing of the socket. I will remove the while loop as you suggest because in this issue and implementation there is no use of looping. A later PR might implement the loop anyway 👍  Thank you!

**Comment by kappsegla** [comment]
This PR might have to make some changes after #24 is done and merged.

**Review by Win-ther — APPROVED** [review]

File: src/main/java/org/fungover/thunder/ClientHandler.java [hunk 2]
```diff
@@ -1,41 +1,33 @@
...
+    public void handleConnection(Socket clientSocket) {
+        try {
+            while (!clientSocket.isClosed()) {
+                System.out.println("New client: " + clientSocket.getInetAddress().getHostName());
+                if (packageReader.isValidConnection(clientSocket)) {
+                    clients.add(clientSocket);
+                } else {
+                    clientSocket.close();
                 }
             }
```
Comment (Win-ther) [inline src/main/java/org/fungover/thunder/ClientHandler.java:25]: The while-loop disconnects the client after connecting because isValidConnection() will return false the second loop.
We need the while-loop to continue listening for more packages from the client, up until the client sends the disconnect package.
So maybe we need some other check where we close the socket if it is a duplicate connection and not only if isValidConnection() fails? Or since one connection can only send one connect and recieve one connack response, limit the times one client can check the connection?

**Review by Win-ther — CHANGES_REQUESTED** [review]
The client gets disconnected after connecting because isValidConnection runs every loop and returns false after first loop, closing the socket. Other than that the code looks good.

File: src/main/java/org/fungover/thunder/ClientHandler.java (hunk 2 above)
Comment (vonfredd) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]: > So maybe we need some other check where we close the socket if it is a duplicate connection and not only if isValidConnection() fails? Or since one connection can only send one connect and recieve one connack response, limit the times one client can check the connection?

There is an issue for the disconnection handling. So that feature will come later.

> The while-loop disconnects the client after connecting because isValidConnection() will return false the second loop.
> We need the while-loop to continue listening for more packages from the client, up until the client sends the disconnect package.

#16 is the only package that is being sent right now. I think packagehandler gets modified when other functions are added. But I can remove the while loop again if you want and just close the socket after adding it? I brought the loop back this time because I consideret it possible that we need a while loop in ClientHandler class after all 😄

Comment (vonfredd) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]:
```suggestion
   public void handleConnection(Socket clientSocket) {
        try {
            while (!clientSocket.isClosed()) {
                System.out.println("New client: " + clientSocket.getInetAddress().getHostName());
                if (packageReader.isValidConnection(clientSocket)) {
                    clients.add(clientSocket);
                }
            }
            clientSocket.close();
    } catch(
    Exception e)
    {
        e.printStackTrace();
    }
}
```

This might be an option?

Comment (vonfredd) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]:
```suggestion
public void handleConnection(Socket clientSocket) {
        try {
            if (packageReader.isValidConnection(clientSocket)) {
                System.out.println("New client: " + clientSocket.getInetAddress().getHostName());
                clients.add(clientSocket);
            } else {
                //Disconnect client/close socket
            }
            while (!clientSocket.isClosed()) {
                //Logic to read from or disconnect client.
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

Is it something like this you would suggest? @Win-ther

Comment (Win-ther) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]: > There is an issue for the disconnection handling. So that feature will come later.
>
Yes I know, I have assigned myself to the issue and I'm working on it 



> #16 is the only package that is being sent right now. I think packagehandler gets modified when other functions are added. But I can remove the while loop again if you want and just close the socket after adding it? I brought the loop back this time because I consideret it possible that we need a while loop in ClientHandler class after all 😄
> 
> Could you add some code? Would be easier for me to see what you suggest 👍

No I think we need a loop in clienthandler. The problem is that the clientsocket gets closed instantly after the CONNECT message is recieved and CONNACK is sent. 
```suggestion
    public void handleConnection(Socket clientSocket) {
    try {
                if (packageReader.isValidConnection(clientSocket)) {
                    System.out.println("New client: " + clientSocket.getInetAddress().getHostName());
                    clients.add(clientSocket);
                } else{
                    clientSocket.close();
                }
            while (!clientSocket.isClosed()) {
                //ToDo: Listen for packets ex. disconnect or ping
            }
```
Here is a quick suggestion, since we only need to connect once. The isValidConnection()-call can be outside the loop, and have the loop listen for future packets that will be implemented in other Issues

Comment (Win-ther) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]: > Is it something like this you would suggest? @Win-ther

Yes that looks good, I think I just commented the same as you suggested. Sorry it took some time, I had some other stuff to do😅😬

Comment (vonfredd) [reply src/main/java/org/fungover/thunder/ClientHandler.java:25]: Great! I did not understand at first, but I am happy we ended up with the same solution 😃 Don't worry, the conversation was set to resolved so I wasnt sure you would be noticed of my response. Thanks for feedback, I will update the code.

**Comment by vonfredd** [comment]
@kappsegla Do I add the tests in this PR to cover SonarCloud expectations, or do I create an issue that creates the tests for all the old and new classes before merging this?

**Comment by kappsegla** [comment]
> @kappsegla Do I add the tests in this PR to cover SonarCloud expectations, or do I create an issue that creates the tests for all the old and new classes before merging this?

If we can write unit tests for the code they belong to the PR. It's a needed part both for our automatic CI but also for reviewers to check and learn how the new code is expected to work from.

**Review by marcusju23 — APPROVED** [review]
Looks good! 👍

**Comment by vonfredd** [comment]
> The code looks good and it works when I test it. Sonarclouds Quality Gate failed though, is this something we can ignore right now and merge anyway? Maybe something to look at in another issue? I will approve right now since I want it to be able to merge if we can ignore the Qualite Gate.

The sonarcloud reacts because no old code has tests. So I also think that would be issued to fix, but ignored for now 😄 .
